name: ntcdcrypto
description: ntc_dcrypto is a module dart cryptography. Includes utility classes for encryption in the Dart programming.
version: 0.2.0
#author: NghiaTC
homepage: https://github.com/congnghia0609/ntc_dcrypto

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
